spring:
  profiles:
    active: dev
server:
  port: 7070
eureka:
  client:
    # 通过下面的两个false来表明自己是一个eureka server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/