spring:
  application:
    name: service-core
  profiles:
    active: dev
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      # 因为启用了basic认证
      defaultZone: http://gary:123456@localhost:7070/eureka/