eureka:
  instance:
    # client发送心跳给server端的频率,默认30秒
    # 如果该instance实现了HealthCheckCallback,并决定让自己unavailable的话,则该instance也不会接收到流量
    lease-renewal-interval-in-seconds: 30
    # server至上一次收到client的心跳之后,等待下一次心跳的超时时间,在这个时间内若没收到下一次心跳,则移除该instance,默认90秒
    lease-expiration-duration-in-seconds: 90