server:
  port: 7060
spring:
  application:
    name: config-server
  # 默认是从git取,改为使用本地
  profiles:
    active: native
  cloud:
    config:
      server:
        default-profile: dev
        native:
          # 配置文件目录
          search-locations: classpath:/config
  rabbitmq:
    host: localhost
    port: 5672
    username: gary
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
          - 'bus-refresh'
eureka:
  client:
    serviceUrl:
      defaultZone: http://gary:123456@localhost:7070/eureka/