eureka:
  client:
    serviceUrl:
      defaultZone: http://gary:123456@localhost:7070/eureka/
server:
  port: 8281
spring:
  application:
    name: service-rest-ribbon
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 默认1s,在com.netflix.hystrix.HystrixCommandProperties的default_executionTimeoutInMilliseconds属性
            timeoutInMilliseconds: 3000